language: r

bioc_required: true

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: KIRZ30AJ6aQMH8fRNmqdXgdBfGr1/xfN3Gd6GF+TmM05H4HKcqRu90baC4FaE3nX9QVFuN5kVAQ915Tb1KCsoFxQTOP7kz1Yz/zvrBl7NEwAqLyUc+ou5bYvJtAilEoay79nrDyETiQ+BEk4Uo3p5FI/OILeqru6m/yDUPkyN64=

env:
  global:
    - _R_CHECK_TIMINGS_="0"  
