on:
  push:
    branches: master

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: devel

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-devel-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-devel-

      - name: Install dependencies
        run: |
          if (!requireNamespace("Rcpp", quietly = TRUE)) install.packages("Rcpp", repos="https://rcppcore.github.io/drat")
          if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
          if (!requireNamespace("GenomicFeatures", quietly = TRUE)) BiocManager::install("GenomicFeatures")
          if (!requireNamespace("ggbio", quietly = TRUE)) BiocManager::install("ggbio")
          if (!requireNamespace("derfinder", quietly = TRUE)) BiocManager::install("derfinder")
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("pkgdown")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
