on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: macOS-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: devel

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-devel-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: macOS-r-devel-

      - name: Install dependencies
        run: |
          if (!requireNamespace("Rcpp", quietly = TRUE)) install.packages("Rcpp", repos="https://rcppcore.github.io/drat")
          if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
          if (!requireNamespace("GenomicFeatures", quietly = TRUE)) BiocManager::install("GenomicFeatures")
          if (!requireNamespace("ggbio", quietly = TRUE)) BiocManager::install("ggbio")
          if (!requireNamespace("derfinder", quietly = TRUE)) BiocManager::install("derfinder")
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
